# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-08-28 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_netimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetImage',
        ),
    ]
